### PR TITLE
fix: export non-Procedures TypeScript types

### LINKED ISSUE #320: rspc router doesn't export types that implement `specta::Type`
Cargo.toml

```toml
specta = { version = "=2.0.0-rc.20", features = ["serde"] }
rspc = { version = "0.3" }
```

main.rs

```rs
use specta::Type;

pub struct RouterContext {}

#[derive(Type, Deserialize, Serialize)]
pub struct SearchInput {
    query: String,
}

#[derive(Type, Deserialize, Serialize)]
pub struct SearchResponse {
    results: Vec<String>,
}

pub fn search(ctx: RouterContext, input: SearchInput) -> SearchResponse {
    SearchResponse {
        results: vec![format!("searching for {}", input.query)],
    }
}

let config = Config::new()
    .export_ts_bindings(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/api-bindings.ts"));

let router = Router::<RouterContext>::new()
    .config(config)
    .query("search", |t| t(search))
    .build();
```

Exported types:

api-bindings.ts

```ts
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "search", input: SearchInput, result: SearchResponse },
    mutations: never,
    subscriptions: never
};
```

As you can see that the `SearchInput` and `SearchResponse` are not exported.

### PR DESCRIPTION
**Pull request by espeon**
Should close #320.

Typemaps should now be correctly merged and exported. Let me know of any issues or things I've overlooked.

### CODE REVIEW

**Comment by yuezk** [comment]
This PR fixes the issue. But it couldn't handle the generic type. For example, the following code:

```rs
#[derive(Debug, Serialize, Type)]
pub(crate) struct Success<T: Serialize + Type = ()> {
  data: T,
}
```
...will produce:

```ts
export type Success = { data: T };
```

But previously with the older versions crates:

```toml
specta = "=2.0.0-rc.1"
specta-macros = "=2.0.0-rc.1"
rspc = { version = "1.0.0-rc.5", features = ["tauri"] }
```

It can produce the correct types.
```ts
export type Success<T> = { data: T }
```

File: src/legacy/router.rs [hunk 1]
```diff
@@ -161,15 +161,19 @@ export type Procedures = {{
...
+                    &config,
+                    &FunctionResultVariant::Value(ty.inner.clone()),
+                    &self.type_map,
+                )
+                .unwrap(),
             )
-            .unwrap()
         }) {
-            writeln!(file, "\n{}", export)?;
+            writeln!(file, "\nexport type {} = {};", name, export)?;
```
Comment (yuezk) [inline src/legacy/router.rs:176]: After looking into the [export implementation](https://github.com/specta-rs/specta/blob/13c74804f510d4002c58750717e6c532effdfa87/specta-typescript/src/typescript.rs#L148) of the `special-typescript` creation, I found that we can use the `export_named_datatype` function it provides. 

This will also fix the problem in my comment https://github.com/specta-rs/rspc/pull/323#issuecomment-2510572276

```rs
for export in self.type_map.iter().map(|(_, ty)| {
    export_named_datatype(
        &config,
        ty,
        &self.type_map,
    )
    .unwrap()
}) {
    writeln!(file, "\n{}", export)?;
}
```

File: src/legacy/resolver.rs [hunk 2]
```diff
@@ -122,5 +122,8 @@ pub fn typedef<TArg: Type, TResult: Type>(defs: &mut TypeMap) -> ProcedureDataTy
     let mut type_map = TypeMap::default();
     let arg_ty = TArg::reference(&mut type_map, &[]).inner;
     let result_ty = TResult::reference(&mut type_map, &[]).inner;
+
+    defs.append(&mut type_map);
```
Comment (oscartbeaumont) [inline src/legacy/resolver.rs:126]: We would be better off removing the `type_map` variable and then using `defs` instead of it.

Would achieve the same effect but cleaner and probally slightly more efficiently.

**Review by oscartbeaumont — CHANGES_REQUESTED** [review]
Happy to merge once the comments are addressed. I do agree with @yuezk's comment.

Thanks for taking the time to do a PR and thanks @yuezk for the feedback!

File: src/legacy/resolver.rs (hunk 2 above)
Comment (espeon) [reply src/legacy/resolver.rs:126]: Ahh, somehow missed that, thanks!
